import { defineConfig } from "tsdown"

export default defineConfig([
  {
    entry: ["src/main.ts"],

    format: ["esm"],
    target: "es2022",
    platform: "node",

    sourcemap: true,
    clean: true,
    removeNodeProtocol: false,

    env: {
      NODE_ENV: "production",
    },
  },
  {
    // Bridge build: separate entry. The bridge is the native-messaging
    // host the browser extension talks to (spawned by Chrome / Edge,
    // not by github-router). It exposes a localhost WS so github-router
    // can dispatch tool calls in. Bundles the ws dep into one file so
    // the NMH manifest's `path` field can point at a single launcher
    // (the .bat / .sh shim generated by native-host-installer.ts).
    entry: ["src/browser-bridge/index.ts"],
    outDir: "dist/browser-bridge",

    format: ["esm"],
    target: "es2022",
    platform: "node",

    sourcemap: false,
    clean: false,
    removeNodeProtocol: false,

    env: {
      NODE_ENV: "production",
    },

    // Bundle the ws dep so the bridge can run from a single file with
    // no node_modules lookup at the NMH launch path.
    noExternal: ["ws"],
  },
  {
    // Tree-sitter parse worker: separate entry. Spawned via worker_threads by
    // src/lib/tree-sitter-pool/pool.ts to parallelize structural-pass parses
    // off the main event loop. Needs its own bundled file because a worker is
    // loaded by file PATH (not imported into the main bundle); the pool's
    // resolveWorkerPath() looks for dist/lib/tree-sitter-pool/worker.js here.
    // web-tree-sitter is left external (resolved from node_modules at runtime,
    // same as the main bundle) — it carries a .wasm sidecar that must not be
    // inlined.
    entry: ["src/lib/tree-sitter-pool/worker.ts"],
    outDir: "dist/lib/tree-sitter-pool",

    format: ["esm"],
    target: "es2022",
    platform: "node",

    sourcemap: false,
    clean: false,
    removeNodeProtocol: false,

    env: {
      NODE_ENV: "production",
    },
  },
])

