import { defineConfig } from "tsdown"

export default defineConfig([
  {
    entry: ["src/main.ts"],

    format: ["esm"],
    target: "es2022",
    platform: "node",

    sourcemap: true,
    clean: true,
    removeNodeProtocol: false,

    env: {
      NODE_ENV: "production",
    },
  },
  {
    // Bridge build: separate entry. The bridge is the native-messaging
    // host the browser extension talks to (spawned by Chrome / Edge,
    // not by github-router). It exposes a localhost WS so github-router
    // can dispatch tool calls in. Bundles the ws dep into one file so
    // the NMH manifest's `path` field can point at a single launcher
    // (the .bat / .sh shim generated by native-host-installer.ts).
    entry: ["src/browser-bridge/index.ts"],
    outDir: "dist/browser-bridge",

    format: ["esm"],
    target: "es2022",
    platform: "node",

    sourcemap: false,
    clean: false,
    removeNodeProtocol: false,

    env: {
      NODE_ENV: "production",
    },

    // Bundle the ws dep so the bridge can run from a single file with
    // no node_modules lookup at the NMH launch path.
    noExternal: ["ws"],
  },
])

